### ISSUE TITLE
Device automation schema not yet included

### ISSUE THREAD

**Issue by eavanvalkenburg** [keesschollaart81/vscode-home-assistant#265] opened 2020-03-08 13:45 UTC
The new GUI based automations are super handy but they introduced a new type of action, for Devices, but those are not yet included in the schema's, and I also could not find what the full schema for those kinds of actions is, but since making small changes in your automation.yaml is quite convenient for more complex automations it would be nice to not get an error for this type.

```YAML
  - device_id: 389465782634 (GUID)
    domain: <domain>
    entity_id: <domain.entity>
    type: <>
```

and/or point to a repository containing your Home Assistant Configuration

**Comment by keesschollaart81** [comment] 2020-03-08 14:16
Duplicate of #156 should be fixed with #264

**Comment by keesschollaart81** [comment] 2020-03-08 14:18
Or am I missing something?

**Comment by eavanvalkenburg** [comment] 2020-03-08 16:15
Missed that one, and found this page https://www.home-assistant.io/integrations/device_automation/, so created a PR for the schema.

**Closed** 2020-05-14 18:42 UTC
Labels: wontfix, yaml
