### ISSUE TITLE
Pasted code identation issue, bug or wrong setting?

### ISSUE THREAD

**Issue by krasatos** [keesschollaart81/vscode-home-assistant#933] opened 2021-01-20 10:03 UTC
Copy/pasting any yaml block, will result in the first line of the block getting extra identation.
Hitting crtl+z after the paste, brings the first line back to its place.

Examples in gifs:
![yaml_paste_identation](https://user-images.githubusercontent.com/1773624/105158662-e687ce00-5b16-11eb-8072-bb7e12399b28.gif)

![yaml_paste_identation2](https://user-images.githubusercontent.com/1773624/105159177-7594e600-5b17-11eb-83a0-5baa039b47ed.gif)

Is this a feature trying to help me out? :)
If so, can i disable it?

I have posted it on the vscode addon github. 
Posting here as i suspect its possibly related to https://github.com/keesschollaart81/vscode-home-assistant/issues/26?

Extension runs in:
- [ ] VS Code for Desktop 
- [X] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

Using the extension through browser.

**Comment by frenck** [comment] 2021-01-21 20:25
Duplicate of #622

**Closed by frenck** 2021-01-21 20:25 UTC
Labels: bug
