### ISSUE TITLE
Yaml error when adding fields property

### ISSUE THREAD

**Issue by stefancvetkovic** [keesschollaart81/vscode-home-assistant#946] opened 2021-01-22 08:31 UTC
I have my scripts organised like this:
`script: !include_dir_named scripts/`
when I put directly to my config, my vs is normal (no red lines) -> https://i.imgur.com/KNoCfK1.png
and here it is in separate file https://i.imgur.com/d07nV6v.png
https://paste.ubuntu.com/p/6k4D8pk2Xr/ this is the test script

What could be a problem and how to fix it? Thanks

**Comment by frenck** [comment] 2021-01-22 08:40
Duplicate of #483

**Closed by frenck** 2021-01-22 08:40 UTC
Labels: yaml
