### ISSUE TITLE
YAML auto indentation issue

### ISSUE THREAD

**Issue by VDRainer** [keesschollaart81/vscode-home-assistant#622] opened 2020-09-13 15:05 UTC
After reading 1 & 2 👆, type your issue here and please include the related YAML code like this:

Auto indentation adds indents after new lines, also on copy and pasting code blocks, indentations are added.

```YAML
every:
   - yaml
```

and/or point to a repository containing your Home Assistant Configuration
https://github.com/hassio-addons/addon-vscode/issues/128

**Comment by frenck** [comment] 2020-09-14 05:50
"Auto indentation adds indents after new lines"

That is the correct behavior...

**Comment by VDRainer** [comment] 2020-09-14 06:45
... **after** new lines.
I think the gif makes the issue clear?

**Comment by frenck** [comment] 2020-09-14 06:58
gif?

I only see this text:

![image](https://user-images.githubusercontent.com/195327/93053684-7cdb4d00-f668-11ea-980d-cdef02a22be8.png)


Maybe a rendering issue in my browser or GitHub?

**Comment by VDRainer** [comment] 2020-09-14 07:04
Well, it's in the issue from the addon-vscode that i linked to.
But here once again.
![yaml_indentation](https://user-images.githubusercontent.com/26381449/93054098-24587f80-f669-11ea-8185-99c7ab40d730.gif)

**Comment by CeeWeasel** [comment] 2020-09-15 01:12
I have been battling this issue for a while now as well. I assumed that my settings for yaml files, the home assistant extension, and/or vscode were just broken somehow, so I finally got used to unindenting everything I pasted.

Some notes:
```
  If you keep pasting an indented item, it will indent it again.
    If you keep pasting an indented item, it will indent it again.
        If you keep pasting an indented item, it will indent it again.
          If you keep pasting an indented item, it will indent it again.
```
You get the idea...

There are also times where the first line in a block of pasted code will be indented an extra time, compared to the rest of the code. For example, if I were to just copy the service chunk from below:
```
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.broken_indentions
      option: 'off'
```

it would look like this when pasted:
```
action:
    - service: input_select.select_option
    data:
      entity_id: input_select.broken_indentions
      option: 'off'
```

**Comment by marvin-w** [comment] 2020-09-19 01:02
Workaround: Copy & Paste => Then CTRL - Z to go back and the indentation is correct with the pasted items still there.

**Comment by hjbotha** [comment] 2020-09-19 08:49
Changing "editor.autoIndent" to "brackets" instead of "full" seems to be somewhat better.

ctrl-shift-p, open settings (json).

**Comment by wixoff** [comment] 2020-10-01 18:45
I think there are two different things being described in this thread:

(1) The @VDRainer original report of indents being added after **blank** lines, which annoys me too!  Disabling this extension reverts to correct behavior - pressing enter on a blank line results in no indent.

(2) The @CeeWeasel note of additional indenting after a paste, which is indeed corrected via CTRL-Z, and I believe is intended behavior.

**Comment by VDRainer** [comment] 2020-12-02 07:17
The issue is still there.

**Comment by mariwing** [comment] 2020-12-12 15:16
I find it strange that this issue is not prioritized to get fixed. I can't even start to count how many hours I have wasted on YAML intendation in general and then when this official Addon even can't do intendation correctly.....

Anyway, I can confirm that this also happens to me. If i use file-type YAML paste works fine, with HomeAssistant the intendation is wrong. I have the YAML extension from Red Hat installed if that matters.

**Comment by frenck** [comment] 2020-12-12 16:31
> I find it strange that this issue is not prioritized to get fixed. 

It's an open-source project. If I knew the fix, I would have provided it. However, since it is open-source, feel free to fix it! That is highly appreciated.

**Comment by lmagyar** [comment] 2021-01-03 14:18
There is a huge effort put into this extension, it would be very helpful, would make editing much faster, but this autoformat/autoindent feature makes the whole extension useless, wasting hours to fight this feature makes me mad. Pasting anything into a yaml breaks the whole formatting. It has never ever formatted anything correctly.

And can't be even turned off, adding ```"editor.autoIndent": "none"``` to setting.json doesn't help.

This "if you don't like it, fix it" attitude keeps average users away from HA. Everybody has different expertise, that not always overlap with technologies behind HA. If you want to keep away average tinkering newbies (like me), fine, yes, average users are always a problem. But this vicious circle ends in a poisonous atmosphere, where nobody will report anything, it doesn't worth the effort, just move on.

**Comment by darsys** [comment] 2021-01-25 16:55
I am having the same results as the OP.  I did not understand this was expected/intended behavior until reading here and doing some example pastes.  I believe the plugin is just attempting to indent the pasted inserted code at the indentation level of the line (of the cursor)  +1.  The ctrl-Z trick works perfect for me as a fix.  Personally I would like to be able to past the code 'raw' somehow, without the extra keystrokes.  Could this be done by creating a setting.  I know one option would be a key bind that includes the paste + ctrl-z and that may be the simplest solution but I try to avoid messing with my configurations so that roaming/installations remain as simple as possible.

I am happy to help address this item and can code but would like to know follow an acceptable direction.

Would it be valuable for me to draft an addition to the troubleshooting guide to explain this behavior?

Thanks for a great tool that saves me tons of time looking up entities, formatting rules and syntax.  This plugin has a very high value for me and I appreciate the work that has been done.

**Comment by darsys** [comment] 2021-01-25 17:15
I understand your frustration with this @mariwing and @lmagyar.  I too agree that it seems like something that is obviously wrong with the behavior and should be addressed.  After familiarizing myself with the issue it is more clear why the issue is more complicated than just flipping a switch, although that is exactly what I would like to try to do with some code.  It is/was very unclear why the pasting is working like it does. I do not believe that @frenk or anyone was disregarding or critical of your input.  He was just communicating that there isn't an obvious fix and if you need it fixed you're best option would be to code it. We all appreciate your feedback and solutions do come without identification and communications of problems.

**Comment by frenck** [comment] 2021-01-25 17:40
> This "if you don't like it, fix it" attitude keeps average users away from HA.

You are kinda making a fool out of yourself there m8. Some bugs are hard. You can shout all you want and make more of those ridiculous statements. But that fixes shit.

Coding is problem-solving. Someone needs to solve the problem. I, for one, don't see a solution. Hopefully, there is someone smarter than me to fix the issue that is here.

>  But this vicious circle ends in a poisonous atmosphere

It is your post that makes it poisonous. Please uninstall everything and go away and buy yourself a commercial product where you can actually try to demand something or actually help out instead of shouting useless crap on people that made this out of love.

**Comment by darsys** [comment] 2021-01-26 02:43
I looked into this a bit more. One thing I found is that code has specific language configurations that can be set in your config. 
 Here is what code added for the home-assistant and yaml languages.

``` javascript
    "[home-assistant]": {

        "editor.insertSpaces": true,
        "editor.tabSize": 2,
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": true
        },
        "editor.autoIndent": "full"
    },
    "[yaml]": {
    
        "editor.insertSpaces": true,
        "editor.tabSize": 2,
        "editor.autoIndent": "advanced",
        "gitlens.codeLens.scopes": [
            "document"
        ],
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": true
        }
    }
```
I edited the  ` "editor.autoIndent": "full" `  to  ` "editor.autoIndent": "advanced" `  in my home-assistant config and the pasting of YAML behaves more as I would expect. I am still researching this but wanted to share my update.

**Comment by frenck** [comment] 2021-01-26 02:51
Interesting @darsys, so you see a difference between using the Red-Hat YAML extension vs the HA extension in the autoIndent behavior setting?

**Comment by darsys** [comment] 2021-01-26 03:03
Yes.  Although, I do not have the Red Hat extension installed, I am using the built [vscode YAML](https://marketplace.visualstudio.com/items?itemName=vscode.yaml) language 'extention' and by selecting YAML language settings the paste happens without sometimes undesirable additional indentation.  I am researching this setting more to see if we can do something that will provide a good solution for everyone.

**Comment by darsys** [comment] 2021-01-26 03:30
Looks like ` "editor.autoIndent": "advanced" ` ignores the indentationRules defined in the [language-configuration.json](https://github.com/keesschollaart81/vscode-home-assistant/blob/master/yaml-language/language-configuration.json). The indentationRules are identical to vscode built in YAML language configuariont (which works as expected).

``` JavaScript

  // Controls whether the editor should automatically adjust the indentation when users type, paste, move or indent lines.
  //  - none: The editor will not insert indentation automatically.
  //  - keep: The editor will keep the current line's indentation.
  //  - brackets: The editor will keep the current line's indentation and honor language defined brackets.
  //  - advanced: The editor will keep the current line's indentation, honor language defined brackets and invoke special onEnterRules defined by languages.
  //  - full: The editor will keep the current line's indentation, honor language defined brackets, invoke special onEnterRules defined by languages, and honor indentationRules defined by languages.
  "editor.autoIndent": "full",

``` 

If making this setting default is a good solution I can update the language-configuration.json and submit a pr but only if others agree this is the correct solution.

**Comment by frenck** [comment] 2021-01-26 07:44
Weird, since we have that setting defined here:

https://github.com/keesschollaart81/vscode-home-assistant/blob/a40e0cae5e1e7d7cf806d7e4a3ec0b591af65b91/package.json#L285

So, that isn't working in that case I would say. The question then becomes: Why :)

**Comment by mariwing** [comment] 2021-01-26 11:46
@frenck  I have read both my own comment and lmagyar multiple times now and I am unable to see that we demand anything or in any way tell anyone that they have to fix anything. Both of us add information about what we tried and we express frustration that it doesn't work. 

It seems like a reminder to read the Code of Conduct (https://www.home-assistant.io/code_of_conduct/) is in place. Telling people that express a view different from your own that they are making a fool of themselves and then ask them to unistall the software and leave don't seem to adhere to the principles written there. 

What I have learned from participating on this issue is that I should not have include my thoughts. That is fair enough. I do understand that it doesn't add value to the issue to express frustration. An issue should be to the point and include only facts. I appologize for this and will strive to do better next time.

**Comment by frenck** [comment] 2021-01-26 11:52
> It seems like a reminder to read the Code of Conduct (home-assistant.io/code_of_conduct) is in place.

This is not a project managed by Home Assistant, this repository does not provide a code of conduct.

The troublesome parts in my opinion have been quotes in my previous response on the matter.

> Telling people that express a view different from your own that they are making a fool of themselves and then ask them to unistall the software and leave don't seem to adhere to the principles written there.

I think it was a likewise response to the quotes. It is open-source. Contributing is done by providing information or fixed. Not by the quoted parts. It didn't add anything besides the frustration (which was funny enough blamed on this issue).

However, that said. I don't care. I rather fix an issue that annoys me as well. Seems that @darsys is on to something. And that is what matters and actually adds something here.

**Comment by frenck** [comment] 2021-01-26 14:19
So I got this out of it:

How Microsoft does it with their Azure extensions (same base):

https://github.com/microsoft/azure-pipelines-vscode/blob/f7d0079da837b27c88bdf24059b7722efd0513b1/package.json#L88-L99

How we do it in this extension: 

https://github.com/keesschollaart81/vscode-home-assistant/blob/a40e0cae5e1e7d7cf806d7e4a3ec0b591af65b91/package.json#L276-L287


They are the same, yet, behave differently. So, my current guess, is that this is a problem in the upstream YAML language server used. However, upgrading that is a bit more work, as there are some breaking changes to deal with.

**Comment by darsys** [comment] 2021-01-26 19:09
> So I got this out of it:
> 
> 
> 
> How Microsoft does it with their Azure extensions (same base):
> 
> 
> 
> https://github.com/microsoft/azure-pipelines-vscode/blob/f7d0079da837b27c88bdf24059b7722efd0513b1/package.json#L88-L99
> 
> 
> 
> How we do it in this extension: 
> 
> 
> 
> https://github.com/keesschollaart81/vscode-home-assistant/blob/a40e0cae5e1e7d7cf806d7e4a3ec0b591af65b91/package.json#L276-L287
> 
> 
> 
> 
> 
> They are the same, yet, behave differently. So, my current guess, is that this is a problem in the upstream YAML language server used. However, upgrading that is a bit more work, as there are some breaking changes to deal with.
> 
> 

I feel like I created confusion. To be clear the 'full' setting behaves incorrectly and the 'advanced' setting behaves as I would expect. The Microsoft YAML extension looks like it defines it as 'advanced', at least in the vscode repo I was in.

**Comment by frenck** [comment] 2021-01-26 19:11
Hmm ok, that would be an easy fix :D

**Comment by darsys** [comment] 2021-01-27 06:38
I verified again tonight to ensure I am getting these same results. Further reading does not help me understand why that behavior changes when I do not see any `  onEnterRules  ` in the current language configuration.  To be honest I am not too unfamiliar with 'language configuration'. I do think the solution of changing the configuration works fine for me and seems to be same setting the YAML language addon is using.

I think others should verify they get the same result and then we can modify the default config.  I will submit a PR if anyone agrees?

**Comment by mariwing** [comment] 2021-01-27 08:46
I can confirm that on my setup switching between full and advanced in settings.json behaves consistently. With 'full' I get the extra intendation of ther first line and with 'advanced' it does not intend and works as expected.

I have not tested if setting advanced instead of full has any other side effects.

**Comment by frenck** [comment] 2021-01-27 09:02
@darsys Do you want to do the honors of creating a PR? 😄 

Nice work!

**Comment by darsys** [comment] 2021-01-27 18:02
#954

**Closed** 2021-01-27 20:43 UTC
Labels: yaml
