### ISSUE TITLE
Person entity in zone trigger

### ISSUE THREAD

**Issue by WildRat** [keesschollaart81/vscode-home-assistant#450] opened 2020-07-29 06:51 UTC
This plugin raises error "String does not match the pattern of "^device_tracker\.(?!_)[\da-z_]+(?<!_)\s?(?:,\s?device_tracker\.(?!_)[\da-z_]+(?<!_))*$"." on zone trigger in autamations with "entity_id: person.somone".

```YAML
trigger:
- entity_id: person.somone
  event: enter
  platform: zone
  zone: zone.home
```

**Comment by frenck** [comment] 2020-07-29 10:37
Duplicate of #443, fixed in #444

**Closed by frenck** 2020-07-29 10:37 UTC
Labels: yaml
