### ISSUE TITLE
Constant "Lost connection with Home Assistant"

### ISSUE THREAD

**Issue by Nornode** [keesschollaart81/vscode-home-assistant#104] opened 2019-09-18 07:54 UTC
Running on Mac OS, configured plugin through the Settings UI (Workspace only)

**HostURL:** https://ha.xxxx.net
**Ignore SSL certs**: Yes ( Even though I do have verified SSL certificate) 
LongLived token: Yes, it's filled.

Homeassistant version: 0.98.1 - Running in a docker container (not hass.io)

**Comment by keesschollaart81** [comment] 2019-10-05 07:52
Should work on 'just' docker as well. What do you see in the logs?

![image](https://user-images.githubusercontent.com/6755359/66251898-bff12880-e755-11e9-8344-a263884f694f.png)

**Comment by Nornode** [comment] 2019-10-10 08:46
Even though I fixed the errors in the files (From logs above) I continue to have re-connect messages in the log output:

```
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
```

**Comment by steve28** [comment] 2019-10-20 14:07
For what it's worth, I am seeing this too - continuous "Lost connection with Home Assistant" notifications.  Logs show:
```
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
[Auth phase] Initializing WebSocket connection to Home Assistant
[Auth Phase] Connecting to Home Assistant...
[Auth phase] Received a message of type auth_required
[Auth phase] Received a message of type auth_ok
(re-)connected to Home Assistant
```

I am using VSCode on MacOS Catalina

**Comment by steve28** [comment] 2019-11-27 00:39
@Nornode are you perhaps using a reverse proxy?

**Comment by Nornode** [comment] 2019-11-28 10:08
Yeah, it is behind an HAproxy on Opnsense.

**Comment by steve28** [comment] 2019-11-28 15:36
@Nornode - interesting.  I also use HAProxy on pfSense... so it could have something to do with that.  I changed my Home Assistant plugin to connect direct to my HA Sever (via HTTP) and I no longer get the error.

**Comment by definitio** [comment] 2020-01-27 16:21
It's not fixed yet.

**Comment by definitio** [comment] 2020-03-27 18:39
It's not fixed yet.

**Comment by NornodeCom** [comment] 2020-03-27 19:15
I switched from Haproxy to Nginx proxy Manager and I don't have the same problem anymore!
It's also way easier to work with compared to Haproxy.....

**Comment by definitio** [comment] 2020-05-26 20:26
It's not fixed yet.

**Comment by definitio** [comment] 2020-07-26 10:50
It's not fixed yet.

**Comment by frenck** [comment] 2020-07-27 18:10
Looking at this issue, it sounds to me this is a reverse proxy issue. Probably release to max request timeout or improper upgrading of the WebSocket connection on the proxy level.

Please try without a reverse proxy to make sure, or, alternatively, provide a detailed reproduction scenario.

**Comment by definitio** [comment] 2020-07-28 16:40
It works without proxy.

**Comment by frenck** [comment] 2020-07-28 17:26
In that case, we can close this issue, as the extension shows the working as intended.
Please make sure your proxy is properly upgrading WebSocket connections on HTTP requests.

**Closed by frenck** 2020-07-28 17:26 UTC

**Comment by JeeCee1** [comment] 2020-12-07 15:17
This issue is occurring to me now. No reverse proxy, just running the add-on from within HomeAssistant, although running HassOS on ProxMox. It occurred after the last upgrade of VStudio code.
Standard warning "code-server is being accessed over an insecure domain. Web views, the clipboard, and other functionality will not work as expected" occurs as expected.
Versions: 
Home Assistant: 0.118.5
Supervisor: 2020.12.6
HassOS 4.17
VSCode: 2.9.1
No entries in the add-on log since add-on startup (yesterday)
Default add-on config (i.e. nothing).

What can I do to debug?

PS: I'm not very experienced with the github etiquette. Should I open a new issue?

**Comment by bbrendon** [comment] 2024-03-18 03:32
Hi @JeeCee1  I've noticed this recently on my system. Constant connect/reconnect. I'm not sure when it started because I tend to ignore extension errors.

**Comment by EuleMitKeule** [comment] 2024-06-06 18:47
I have the same issue and am also using HAProxy on pfSense.

**Comment by loomitz** [comment] 2024-08-09 05:09
I also have the same issue HAProxy + OPNsense

**Comment by harmpter** [comment] 2025-03-03 12:20
I have this issue but I don't use a proxy thingy. Please help me out. 🙏
HA with HAOS running on my RPi4. I havent set up any reverse proxy thing, just plain HA with Nabu Casa. VSCode is running on my windows laptop, in the extension settings I've set the host url to either  `http://192.168.0.222:8123/` or `https://abc---xyz.ui.nabu.casa/` and a valid token. 
Everything works for a while, but every time **a yaml parse fails because I'm in the middle of typing something**, it seems to crash. I get no error messages from the Language Server Output, the first message after crashing is `Connecting to Home Assistant...`. 
Idk if its relevant, but I also get this quite often: `Applying schemas to 24 of your configuration files...` 
Also when it crashes, it also breaks all of my snippets which is frustrating. Can someone help me troubleshoot?
