### ISSUE TITLE
Tag validation 

### ISSUE THREAD

**Issue by balloob** [keesschollaart81/vscode-home-assistant#1058] opened 2021-03-15 00:01 UTC
So this automation in automations.yaml throws a validation error on tag ID. It incorrectly assumes that tag IDs have a specific string format (they should be just strings).

```YAML
automation:
- id: "1613759208429"
  alias: Tag Movie is scanned
  description: ""
  trigger:
    - platform: tag
      tag_id: 04-B1-C6-62-2F-64-80
```

Screenshot from VS Code add-on:
![image](https://user-images.githubusercontent.com/1444314/111088919-b6412800-84e6-11eb-8364-78de0538e771.png)

But... I can't find that annotation in the trigger schema nor can I see it ever being there in the history (and so already fixed). 

Tag schema is here https://github.com/keesschollaart81/vscode-home-assistant/blob/dev/src/language-service/src/schemas/integrations/triggers.ts#L402-L406

**Comment by frenck** [comment] 2021-03-15 12:15
Which versions are you running? (VSCode, Extension, add-on?)

As I cannot reproduce it... 😟 

![image](https://user-images.githubusercontent.com/195327/111152007-83ec0500-8590-11eb-9523-4c2b85cf08f4.png)

**Comment by balloob** [comment] 2021-03-15 17:54
The add-on is 3.1.1. When I go to extensions in VS Code, it doesn't show anything is installed 🤔 

![image](https://user-images.githubusercontent.com/1444314/111198381-b986f300-857c-11eb-84e4-ad9b672019e8.png)

I tried restarting the add-on and the validation shows up again. 

Just FYI, I am doing this inside `automations.yaml`, not inside `configuration.yaml`.

**Comment by frenck** [comment] 2021-03-15 19:01
Add-on v3.1.1, is running v1.14.1 of the extension (is a build-in/bundled extension, thus not listed. You can unhide those in the three dots menu of VSCode shown in the above screenshot).

The JSON schema distributed with this version of the extension has it... Although, I'm unsure why, as it is not defined (and also, cannot reproduce that schema).

So: interesting one.

**Comment by frenck** [comment] 2021-03-23 13:27
Fixed in the current version of the extension and the upcoming version of the add-on:

![image](https://user-images.githubusercontent.com/195327/112153736-e1610100-8be3-11eb-961f-640c9f031598.png)

**Closed by frenck** 2021-03-23 13:27 UTC
Labels: yaml
