### ISSUE TITLE
DeprecationWarning in VScode

### ISSUE THREAD

**Issue by yelkenli1** [keesschollaart81/vscode-home-assistant#2081] opened 2022-05-06 15:24 UTC
Please include the related YAML code: please see warning in VScode that sometimes pops up on start and sometimes when editing my automations or configuration.  I don't find any discussion of this warning. Can you comment and recommend resolution?

```
(node:14148) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./dist/" in the "exports" field module resolution of the package at 
/Users/yelkenli/.vscode/extensions/keesschollaart.vscode-home-assistant-1.29.0/node_modules/home-assistant-js-websocket/package.json.
Update this package.json to use a subpath pattern like "./dist/*".
(Use `Electron --trace-deprecation ...` to show where the warning was created)
```

Find my Home Assistant Configuration here:
[Link to Home Assistant Configuration](<link to repo here>)

Extension runs in:
- [X] VS Code for Desktop 
- [ ] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ ] Windows 
- [X] Mac 
- [ ] Linux 

I'm accessing my files:
- [] From local disk 
- [ ] Via remote SSH 
- [x] Smb
- [ ] Other:

**Comment by frenck** [comment] 2022-05-09 08:29
duplicate of #2019

**Closed by frenck** 2022-05-09 08:29 UTC
Labels: bug
