### ISSUE TITLE
person entity shown as warning for zone trigger (but it is ok to use)

### ISSUE THREAD

**Issue by hkhaka** [keesschollaart81/vscode-home-assistant#608] opened 2020-09-11 21:48 UTC
person.xx is not accepted as a trigger entity_id for automation.
Only device_tracker.xxx is allowed

HA trigger documentation states (https://www.home-assistant.io/docs/automation/trigger/):
ZONE TRIGGER
Zone trigger fires when an entity is entering or leaving the zone. The entity can be either a person, or a device_tracker.

```YAML
- id: person_notifications
  alias: Personer - zonnotifieringar
  trigger:
  - platform: zone
    entity_id: person.siri, person.ella  <-- not accepted
    zone: zone.torasskolan
    event: enter
  - platform: zone
    entity_id: device_tracker.siri_sh_a40, device_tracker.ella_eh_a40   <-- accepted
    zone: zone.torasskolan
    event: leave
```
![image](https://user-images.githubusercontent.com/45568793/92975574-d84ee480-f488-11ea-96ba-61da1c0b608e.png)

Understand that it is a "scheme issue", but not "quite easy" enough for me to fix. :-)

**Comment by frenck** [comment] 2020-09-12 06:05
Duplicate of #443 and #450
Fixed in #444

**Comment by mario-tux** [comment] 2020-09-16 09:39
I upgraded vscode addon to 2.6.0 and it should include https://github.com/keesschollaart81/vscode-home-assistant/ 1.9.0, right? I can still see the warning about the usage of person in zone condition. What's wrong?

**Comment by frenck** [comment] 2020-09-16 10:28
You are absolutely right, it was fixed in the trigger, not the conditions.
Will adjust that right away.

**Closed** 2020-09-16 10:35 UTC
Labels: yaml
